import { createContext, useContext, useEffect, useState, type ReactNode } from 'react'

type Locale = 'en' | 'ar'
const strings = {
  en: { app: 'Anchorboard', tagline: 'Make room for the work that matters.', dashboard: 'Board', guide: 'How it works', addTitle: 'Add a loose end', addHelp: 'Capture it now. Decide when to do it later.', taskName: 'What needs attention?', taskPlaceholder: 'Reply to the design email', minutes: 'Minutes', energy: 'Energy', low: 'Low', medium: 'Medium', high: 'High', add: 'Add to board', today: 'Today’s anchors', empty: 'Your board is clear. Add a loose end to begin.', total: 'planned minutes', calm: 'A calm amount', full: 'A full day', clear: 'Clear board', theme: 'Toggle theme', language: 'العربية', validName: 'Give this task a short name.', validMinutes: 'Use between 5 and 240 minutes.', anchorHint: 'Anchor similar energy levels together to reduce context switching.', guideTitle: 'A gentler way to plan', guideOne: 'Capture', guideOneText: 'Write down small tasks without deciding their exact place in your day.', guideTwo: 'Notice energy', guideTwoText: 'Mark the mental energy each task needs. This is more useful than urgency alone.', guideThree: 'Create an anchor', guideThreeText: 'Work through a few tasks with similar energy in one protected session.', back: 'Back to board' },
  ar: { app: 'أنكوربورد', tagline: 'اترك مساحة للعمل المهم.', dashboard: 'لوحة العمل', guide: 'طريقة الاستخدام', addTitle: 'أضف مهمة معلّقة', addHelp: 'سجّلها الآن، وحدد وقتها لاحقاً.', taskName: 'ما الذي يحتاج إلى انتباه؟', taskPlaceholder: 'الرد على بريد التصميم', minutes: 'الدقائق', energy: 'الطاقة', low: 'منخفضة', medium: 'متوسطة', high: 'عالية', add: 'أضف إلى اللوحة', today: 'مراسي اليوم', empty: 'لوحتك فارغة. أضف مهمة للبدء.', total: 'دقيقة مخططة', calm: 'يوم هادئ', full: 'يوم ممتلئ', clear: 'مسح اللوحة', theme: 'تغيير المظهر', language: 'English', validName: 'اكتب اسماً قصيراً للمهمة.', validMinutes: 'استخدم رقماً بين 5 و240 دقيقة.', anchorHint: 'اجمع المهام ذات مستويات الطاقة المتشابهة لتقليل تبديل السياق.', guideTitle: 'طريقة ألطف للتخطيط', guideOne: 'سجّل', guideOneText: 'اكتب المهام الصغيرة دون تحديد مكانها في يومك.', guideTwo: 'لاحظ الطاقة', guideTwoText: 'حدد الطاقة الذهنية التي تحتاجها المهمة، فهذا أدق من الاستعجال وحده.', guideThree: 'اصنع مرساة', guideThreeText: 'أنجز عدة مهام متشابهة في الطاقة ضمن جلسة محمية.', back: 'العودة إلى اللوحة' }
}
const I18nContext = createContext<{ locale: Locale; t: typeof strings.en; toggleLocale: () => void }>({ locale: 'en', t: strings.en, toggleLocale: () => undefined })
export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>(() => (localStorage.getItem('anchor-locale') as Locale) || 'en')
  useEffect(() => { document.documentElement.dir = locale === 'ar' ? 'rtl' : 'ltr'; document.documentElement.lang = locale; localStorage.setItem('anchor-locale', locale) }, [locale])
  return <I18nContext.Provider value={{ locale, t: strings[locale], toggleLocale: () => setLocale(locale === 'en' ? 'ar' : 'en') }}>{children}</I18nContext.Provider>
}
export const useI18n = () => useContext(I18nContext)